== Key Takeaways

Listening to different leaders from different industries and experiences, there are several shared themes and key learnings

* <<psychological-safety>>
* <<biceps>>
* <<transparency>>
* <<growth-dynamics>>
* <<goals>>
* <<storytelling>>


[[psychological-safety]]
== Psychological Safety

* Regular actionable feedback, in a comfortable way for them
* Empathy
* Build and maintain trust
* Open and honest environment
* "No shaming"

[.notes]
--
A lot of speakers spoke about the importance of psychological safety.

* Ask up front how they would like to receive feedback
* They may require more confirmation than others in the team
* Don't spend all your time on one or two reports, be even.
* Franklin Hu [Stripe] talks about how shame erodes courage and fuels disengagement
--

[[biceps]]
== Psychological Needs

The amygdala in the brain can override rational thinking – We feel threatened when our core needs are at risk

* Belonging
* Improvement/Progress
* Choice
* Equality
* Predictability
* Significance

[.small]
https://www.palomamedina.com/biceps[More here]

[.notes]
--
The amygdala activates when you feel threatened, it's the primal part of the brain that's saved us from extinction.

Thinking of everyones BIPCEPS will help avoid awkward situations, and should help keep people in a safe state.

* Belonging - Sense of community. Threatening this in trials shows that physical pain indicators fire in the brain. No invite to team lunch etc
* Improvement/Progress - Sense of purpose, vision. Towards purpose or improving lives, learning etc.
* Choice - flexibility, autonomy. It's a balance.
* Equality - equal access for resources, time, compensation
* Predictably - Direction of work, time, challenges
* Significance - Do they have an effect? Can they move needles, are they visibility, do they get recognition

Moving desk is an example of a disruption that can threaten all of the needs above.
--

[[transparency]]
== Be Transparent

This affects your relationship with everyone not just your reports.

* Product Management will learn to disbelieve estimates if constantly wrong - own up to failure
+
"Hofstadter's Law: It always takes longer than you expect, even when you take into account Hofstadter's Law."
-- Douglas Hofstadter

[.notes]
--
* Interesting talk by Jonathan Rigby on software estimation
** why do we have it if it's so hard to get right?
** If over promise when it's clear it's not possible you will lose team members
** estimates will become over inflated

--

[[growth-dynamics]]
== Team dynamics change during growth

Changes in teams always affect dynamics.

* Keep security, privacy and quality in mind from day one
* Ensure the team is at the heart of everything
* Be clear on the goal/mission
* Communicate openly
* Hire responsibly

[.notes]
--
Franklin Hu spoke about ensuring that security is a key foundation on which
team knowledge is built.

Joanna Chwastowska talks about how she grew from 3 to 150 people in a year.
Her challenges were around scaling the vision and approach

Several speakers talking about ensuring transparency on putting together job specs
and about communication during the hiring process. "If you're embarrassed about putting something on your job spec, you should address it." Try to elliminate as much bias as possible
--

[[storytelling]]
== Storytelling

* Important for purveying information
* Engaging and trustworthy
* Feynman Technique
1. Teach it to a child
1. Review
1. Organise and Simplify
1. Transmit

[.notes]
--
Kept coming up in different ways throughout the conference

Excellent piece by Nick Means about the story of Eiffel's tower.

1. Teach it to a child
+
Write out what you understand on a piece of paper, using words that can be understood by a child. In doing so you'll identify gaps in your knowledge. 
1. Review
+
Where you're unable to explain, go and research until you have a clearer picture in your mind, ignore jargon and understand in plain terms.
1. Organise and Simplify
+
Review your notes, and organise them into a simple narrative that can be read. Read it out loud. You may need to simplify it further.
1. Transmit
+
Once you're sure you understand something, then you can share this knowledge with another person, or group.
--

[[goals]]
== Have clear goals

* Engage teams to achieve high performance
** Memorable goals
** Creativity trough constraints
** Autonomy with principal
** Motivation by pitch
** Engagement by telling stories

* Crucial to success is being able to define what it looks like
* Don't get bogged down in individual metrics

[.notes]
--
Jose Caldeira talks about how important it is to ensure that the goals are meaningful, powerful and motivational

Whitney O'Banner talks about how teams often get caught up in defining Key Results to go with Objectives that are unmeasurable or unachievable. The first few times you should not worry about targetting metrics. The metrics may not even turn out to have any bearing on how successful the project is.
--

[[define-progression]]
== Defined Progression

Spend time to define progression

* Don't overload new starters
* Build shared vocabulary
* Be clear about focus
* Enable learning new skills
* Acknoledge levelling up
* Makers can multiple people

[.notes]
--
Both Pat Kua, and Melinda Seckington talk about career progression and tracking.

They both have different representations of what the progression looks like.

An idea:
* Produce a spreadsheet with names, skills "HTML", "CSS", "SQL" etc and rate skills
** Beginner ("I probably can't help you")
** Intermediate ("I can help you, if it's not too complicated")
** Experienced ("I'm confident I can help you")
* Define several "Tracks" of progression focusing on different aspects - assign them to roles.
* Define the shape of individuals using a radar chart 